#!/bin/bash
set -e

## Matthew Dorsey
## @ mad-mpikg
## matthew.dorsey@mpikg.mpg.de
## Max Planck Insitute for Colloids and Interfacial Sciences
## 2025.10.08

## FILENAME: programs/bash/util/math/logscsale.sh
## PURPOSE: generate range of values linearly along a logscsale

## MODULES
# none

## PARAMETERES
# nonzero exit value
declare -i NONZERO_EXITCODE=120
# file name
FILENAME="progams/bash/util/math/linlogscale.sh"
# purpose
PURPOSE="generate one value (n) corresponding to range of number (N) between (A) and (B) along either linear or logscale"
# default format string
DEFAULT_FORMAT_STRING="8.5f"

## OPTION PARAMETERS
# boolean for generating along a logarithmic vs a linear scale
declare -i BOOL_LOG=0
# boolean determining if the minimum value has been specified
declare -i BOOL_MINVAL=0
# boolean determnining if the maximum value has been specified
declare -i BOOL_MAXVAL=0
# boolean determining if the total number of values has been specified
declare -i BOOL_NVALS=0
# boolean determining if the current integer has been specified
declare -i BOOL_CURRINT=0
# boolean determining if a format string has been specified
declare -i BOOL_FORMAT=0


## METHODS
# display script used, exit with exitcode
help () {

    ## PARAMETERES
    # none

    ## ARGUMENTS
    # none

    ## SCRIPT
    # first option: exit code
    local exitcode=$1

    ## SCRIPT
    # display script name and purpose
    echo -e "\nFILE: \t ${FILENAME}.sh\nPURPOSE: ${PURPOSE}.\n"
    # display script options
    echo -e "\n ## SCRIPT PROTOCOL ## \n"
    echo -e " -h\t\t| HELP: display options, exit 0."
    echo -e " -L\t\t| generate values along LOG scale (default is LINEAR)."
    echo -e "\n ## SCRIPT MANDATORY PARAEMETERS ## \n"
    echo -e " -A << ARG >>\t| MANDATORY: MINIMUM value assigned to parameter."
    echo -e " -B << ARG >>\t| MANDATORY: MAX value assigned to parameter."
    echo -e " -N << ARG >>\t| MANDATORY: integer representing TOTAL NUMBER of unique values to generate between A and B."
    echo -e " -I << ARG >>\t| MANDATORY: integer representing current INTEGER to generate along scale (script returns value corresponding to n)"
    echo -e ""

    # exit with exit code
    exit $exitcode

}

# display error message, call help with nonzero exit code
display_error () {

    ## PARAMETERS
    # none

    ## ARGUMENTS
    # none

    ## SCRIPT
    # first argument: error message to display
    local err_msg=$1

    ## SCRIPT
    # display error message
    echo -e "\nERROR :: ${FILENAME} :: ${err_msg}.\n"
    help $NONZERO_EXITCODE
}

# check options passed to script call, before script execution
check () {

    ## PARAMETERS
    # none

    ## ARGUMENTS
    # none

    ## SCRIPT
    # check the minimum and maximum values
    if [[ $BOOL_MINVAL -eq 0 && $BOOL_MAXVAL -eq 0 ]]; then
        display_error "must specify a minimum (option -A) and maximum (option -B) value corresponding to the scale"
    elif [[ $BOOL_MINVAL -eq 0 ]]; then
        display_error "must specify a minimum value (option -A). the MIN VAL represents the smallest value generated on the scale."
    elif [[ $BOOL_MAXVAL -eq 0 ]]; then
        display_error "must specify a maximum value (option -B). the MAX VAL represents the largest value generated on the scale."
    fi

    if (( $(echo "$MINVAL > $MAXVAL" | bc -l) )); then
        display_error "the MIN VAL ($MINVAL) is greater than the MAX VAL ($MAXVAL)"
    fi

    # check that the total number of values have been specified
    if [[ $BOOL_NVALS -eq 0 ]]; then
        display_error "must specify an integer number that represents the total number of values the script will generate along the linear or logarithmic scale (option -N)"
    elif [[ $NVALS -lt 1 ]]; then
        display_error "the total number of values generated by the script (option -N) must be greater than or equal to 1"
    fi

    # check the current integer
    if [[ $BOOL_CURRINT -eq 0 ]]; then
        display_error "must specify the current INTEGER (option -I). This a value in between 1 and the TOTAL NUMBER (option -N)."
    elif [[ $CURRINT -lt 1 || $CURRINT -gt $NVALS ]]; then
        display_error "INTEGER (option -I) must be between the 1 and the TOTAL NUMBER ($NVALS)"
    fi

    # if logscale is called, min and max values cannot be negative
    if [[ $BOOL_LOG -eq  1 ]]; then
        # check the minimum value
        if (( $(echo "$MINVAL < 0" | bc -l ) )); then
            display_error "if LOG is called, MIN VAL ($MINVAL) cannot be less than zero"
        fi
        # check the maximum value
        if (( $(echo "$MAXVAL < 0" | bc -l ) )); then
            display_error "if LOG is called, MAX VAL ($MAXVAL) cannot be less than zero"
        fi
    fi

    if [[ $BOOL_FORMAT -eq 0 ]]; then
        # if a format string has not been specified
        # use the default
        FORMAT=${DEFAULT_FORMAT_STRING}
    fi
}

# log10 function, echos log10 of first argument passed to method
log10 (){

    ## PARAMETERS
    # none

    ## ARGUMENTS
    # number to perform log10 operation on
    local NUM_LOG=$1

    ## SCRIPT
    # perform log10 operation on number
    echo "l(${NUM_LOG})/l(10)" | bc -l
}

# pow10 function, echos 10 to the power of the first argument passed to method
pow10 () {

    ## PARAMETERS
    # none

    ## ARGUMENTS
    # number to perform pow10 operation on
    local NUM_POW=$1

    ## SCRIPT
    # perform pow10 operation
    VAL=$( echo "l(10)" | bc -l )
    VAL=$( echo "(${VAL})*(${NUM_POW})" | bc -l )
    echo "e(${VAL})" | bc -l
}

# generate number along logscale, echo
logscale () {

    ## PARAMETERS
    # minimum number on a log10 scale
    MIN_VAL_LOG10=$( log10 ${MINVAL} )
    # maximum number on a log10 scale
    MAX_VAL_LOG10=$( log10 ${MAXVAL} )
    # integer, location along scale to generate number
    declare -i NUM=$CURRINT

     ## ARGUMENTS
     # none

     ## SCRIPT
     # generate the parameter along scale
     scale=$( echo "(( $NUM - 1 ) / ( ${NVALS} - 1 ))" | bc -l )
     scale=$( echo "(${scale} * (${MAX_VAL_LOG10} - ${MIN_VAL_LOG10}) + ${MIN_VAL_LOG10})" | bc -l )
     scale=$( pow10 "$scale" )
     echo $(printf "%${FORMAT}\n" "${scale}")
}

# generate number along a linear scale, echo
linscale () {

    ## PARAMETERS
    # minimum number on a linear scale
    MIN_VAL_LIN=${MINVAL}
    # maximum value along a linear scale
    MAX_VAL_LIN=${MAXVAL}
    # integer, location along scale to generate number
    declare -i NUM=$CURRINT

    ## ARGUMENTS
    # none

    ## SCRIPT
    # generate the parameter along the linear scale
    scale=$( echo "(($NUM - 1 ) / ( ${NVALS} - 1 ))" | bc -l )
    scale=$( echo "(${scale} * (${MAX_VAL_LIN} - ${MIN_VAL_LIN}) + ${MIN_VAL_LIN})" | bc -l )
    echo $(printf "%${FORMAT}\n" "${scale}")
}

## OPTIONS
# parse options
while getopts "hA:B:N:I:Lf:" opt; do
    case $opt in
        h) # call help
            help 0 ;;
        A) # minimum value
            declare -i BOOL_MINVAL=1
            MINVAL=${OPTARG} ;;
        B) # maximum value
            declare -i BOOL_MAXVAL=1
            MAXVAL=${OPTARG} ;;
        N) # total number of values
            declare -i BOOL_NVALS=1
            declare -i NVALS=${OPTARG} ;;
        I) # current value corresponding to scale
            declare -i BOOL_CURRINT=1
            declare -i CURRINT=${OPTARG} ;;
        L) # log vs. linear scale
            declare -i BOOL_LOG=1 ;;
        f) # specify format string
            declare -i BOOL_FORMAT=1
            FORMAT=${OPTARG} ;;
        ?) # unspecified flag
            help $NONZERO_EXITCODE
    esac
done

## ARGUMENTS
# none

## SCRIPT
# check options
check

if [[ $BOOL_LOG -eq 1 ]]; then
    echo $( logscale )
else
    echo $( linscale )
fi
